#!/bin/bash

cd $HOME
git clone git://github.com/derwiki/dotfiles.git
ln -s dotfiles/.vimrc .vimrc
ln -s dotfiles/.screenrc .screenrc
ln -s dotfiles/.gitconfig .gitconfig

mkdir $HOME/bin
mkdir $HOME/src

git clone git://github.com/derwiki/scripts.git
echo >> $HOME/.profile
echo "# autogenerated by github.com/scripts.git/bootstrap.sh" >> $HOME/.bash_profile
echo "source $HOME/scripts/aliases.sh" >> $HOME/.bash_profile

# At the time this was created, github was acting really flaky
# git clone https://github.com/git/git.git $HOME/src/git
git clone git://git.kernel.org/pub/scm/git/git.git $HOME/src/git
cd $HOME/src/git
make && make install && echo "`git` compiles successfully"
echo "alias git='$HOME/bin/git'" >> $HOME/.bash_profile

