#!/bin/bash

cd $HOME
if [ ! -d $HOME/dotfiles ]
  then
    echo "No existing $HOME/dotfiles, cloning..."
    git clone git://github.com/derwiki/dotfiles.git
  else
    echo "Found $HOME/dotfiles, updating..."
    cd $HOME/dotfiles
    git fetch && git reset --hard origin/master
fi

=======
for dotfile in .bashrc .vimrc .tmux.conf .gitconfig .bash_profile; do
  rm $HOME/$dotfile
  ln -s $HOME/dotfiles/$dotfile $HOME/$dotfile
done

for folder in bin src; do
  if [ ! -d $HOME/$folder ]; then mkdir $HOME/folder; fi
done

if [ ! -d $HOME/scripts ]
  then
    git clone git://github.com/derwiki/scripts.git
    echo >> $HOME/.profile
    echo "# autogenerated by github.com/scripts.git/bootstrap.sh" >> $HOME/.bash_profile
    echo "source $HOME/scripts/helpers.sh" >> $HOME/.bash_profile
fi

# set up git completion
if [ ! -f $HOME/scripts/git-completion.bash ]
  then
    curl -L https://github.com/git/git/raw/master/contrib/completion/git-completion.bash > $HOME/scripts/git-completion.bash
    echo "source $HOME/scripts/git-completion.bash" >> $HOME/.bash_profile
fi

# At the time this was created, github was acting really flaky
# git clone https://github.com/git/git.git $HOME/src/git
if [ ! -d $HOME/src/git ]
  then
    git clone git://git.kernel.org/pub/scm/git/git.git $HOME/src/git && \
      cd $HOME/src/git && \
      make && make install && \
      echo "'git' compiles successfully" && \
      echo "alias git='$HOME/bin/git'" >> $HOME/.bash_profile
fi
