#!/bin/bash
bundle exec rake assets:clean
bundle exec rake assets:precompile
git add public/assets
echo About to git rm $(git status public/assets | grep deleted | cut -d' ' -f 5)
git rm $(git status public/assets | grep deleted | cut -d' ' -f 5)
